
    # Documentation
    - env: GHCVER=7.10.3 LIBRARY=documentation
      addons: { apt: { packages: [ghc-7.10.3], sources: [hvr-ghc] } }

    # Core
    - env: GHCVER=8.0.1 LIBRARY=gogol-core
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.3 LIBRARY=gogol-core
      addons: { apt: { packages: [ghc-7.10.3], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.3 LIBRARY=gogol
      addons: { apt: { packages: [ghc-7.10.3], sources: [hvr-ghc] } }

    # Priority
    - env: GHCVER=8.0.1 LIBRARY=gogol-compute
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-drive
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-appengine
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-storage
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-oauth2
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-gmail
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }

    # Remainder
    - env: GHCVER=8.0.1 LIBRARY=gogol-adexchange-buyer
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-adexchange-seller
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-admin-datatransfer
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-admin-directory
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-admin-emailmigration
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-admin-reports
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-adsense
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-adsense-host
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-affiliates
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-analytics
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-android-enterprise
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-android-publisher
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-apps-activity
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-apps-calendar
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-apps-licensing
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-apps-reseller
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-apps-tasks
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-appstate
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-autoscaler
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-bigquery
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-billing
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-blogger
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-books
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-civicinfo
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-classroom
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-cloudmonitoring
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-cloudtrace
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-container
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-customsearch
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-dataflow
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-dataproc
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-datastore
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-debugger
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-deploymentmanager
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-dfareporting
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-discovery
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-dns
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-doubleclick-bids
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-doubleclick-search
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-firebase-rules
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-fitness
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-fonts
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-freebasesearch
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-fusiontables
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-games
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-games-configuration
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-games-management
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-genomics
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-groups-migration
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-groups-settings
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-identity-toolkit
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-kgsearch
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-latencytest
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-logging
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-maps-coordinate
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-maps-engine
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-mirror
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-monitoring
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-pagespeed
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-partners
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-people
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-play-moviespartner
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-plus
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-plus-domains
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-prediction
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-proximitybeacon
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-pubsub
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-qpxexpress
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-replicapool
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-replicapool-updater
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-resourcemanager
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-resourceviews
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-script
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-sheets
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-shopping-content
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-siteverification
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-spectrum
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-sqladmin
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-storage-transfer
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-tagmanager
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-taskqueue
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-translate
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-urlshortener
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-useraccounts
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-vision
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-webmaster-tools
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-youtube
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-youtube-analytics
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=gogol-youtube-reporting
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }

    # Examples
    - env: GHCVER=8.0.1 LIBRARY=gogol-examples
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
